/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DiscoveredBusiness {
  'name' : string,
  'website' : string,
  'address' : string,
  'category' : string,
  'rating' : string,
  'phone' : string,
}
export interface DiscoveredProduct {
  'categories' : string,
  'brands' : string,
  'productName' : string,
  'imageUrl' : string,
}
export interface FamilyMember {
  'id' : bigint,
  'occupation' : string,
  'bloodType' : string,
  'relationship' : Relationship,
  'name' : string,
  'medicalConditions' : Array<string>,
  'isPublic' : boolean,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpResponse {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface PersonProfile {
  'bio' : string,
  'name' : string,
  'htmlUrl' : string,
  'login' : string,
  'avatarUrl' : string,
}
export type Relationship = { 'grandchild' : null } |
  { 'grandparent' : null } |
  { 'other' : null } |
  { 'child' : null } |
  { 'sibling' : null } |
  { 'spouse' : null } |
  { 'parent' : null };
export interface TransformArg {
  'context' : Uint8Array,
  'response' : HttpResponse,
}
export interface UserProfile {
  'bio' : string,
  'occupation' : string,
  'bloodType' : string,
  'dateOfBirth' : string,
  'name' : string,
  'photoUrl' : string,
  'isPrivate' : boolean,
}
export interface _SERVICE {
  'addFamilyMember' : ActorMethod<[FamilyMember], undefined>,
  'addMarriage' : ActorMethod<[Principal, Principal, string], undefined>,
  'claimAdmin' : ActorMethod<[], boolean>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getFamilyTree' : ActorMethod<[], Array<FamilyMember>>,
  'getFamilyTreeForUser' : ActorMethod<[Principal], Array<FamilyMember>>,
  'getFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getPublicProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[Principal, Principal], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchBusinesses' : ActorMethod<
    [string, string],
    { 'ok' : Array<DiscoveredBusiness> } |
      { 'err' : string }
  >,
  'searchPeople' : ActorMethod<
    [string],
    { 'ok' : Array<PersonProfile> } |
      { 'err' : string }
  >,
  'searchProducts' : ActorMethod<
    [string],
    { 'ok' : Array<DiscoveredProduct> } |
      { 'err' : string }
  >,
  'transformHttpResponse' : ActorMethod<[TransformArg], HttpResponse>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];