/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Relationship = IDL.Variant({
  'other' : IDL.Text,
  'child' : IDL.Null,
  'sibling' : IDL.Null,
  'spouse' : IDL.Null,
  'parent' : IDL.Null,
});
export const FamilyMember = IDL.Record({
  'id' : IDL.Nat,
  'occupation' : IDL.Text,
  'bloodType' : IDL.Text,
  'relationship' : Relationship,
  'name' : IDL.Text,
  'medicalConditions' : IDL.Vec(IDL.Text),
  'isPublic' : IDL.Bool,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'occupation' : IDL.Text,
  'bloodType' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'name' : IDL.Text,
  'photoUrl' : IDL.Text,
  'isPrivate' : IDL.Bool,
});
export const Profile = IDL.Record({
  'id' : IDL.Principal,
  'bio' : IDL.Text,
  'occupation' : IDL.Text,
  'bloodType' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'name' : IDL.Text,
  'photoUrl' : IDL.Text,
  'isPrivate' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFamilyMember' : IDL.Func([FamilyMember], [], []),
  'addMarriage' : IDL.Func([IDL.Principal, IDL.Principal, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFamilyTree' : IDL.Func([], [IDL.Vec(FamilyMember)], ['query']),
  'getFamilyTreeForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(FamilyMember)],
      ['query'],
    ),
  'getFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
  'getPublicProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func(
      [IDL.Principal, IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Relationship = IDL.Variant({
    'other' : IDL.Text,
    'child' : IDL.Null,
    'sibling' : IDL.Null,
    'spouse' : IDL.Null,
    'parent' : IDL.Null,
  });
  const FamilyMember = IDL.Record({
    'id' : IDL.Nat,
    'occupation' : IDL.Text,
    'bloodType' : IDL.Text,
    'relationship' : Relationship,
    'name' : IDL.Text,
    'medicalConditions' : IDL.Vec(IDL.Text),
    'isPublic' : IDL.Bool,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'occupation' : IDL.Text,
    'bloodType' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'photoUrl' : IDL.Text,
    'isPrivate' : IDL.Bool,
  });
  const Profile = IDL.Record({
    'id' : IDL.Principal,
    'bio' : IDL.Text,
    'occupation' : IDL.Text,
    'bloodType' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'photoUrl' : IDL.Text,
    'isPrivate' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFamilyMember' : IDL.Func([FamilyMember], [], []),
    'addMarriage' : IDL.Func([IDL.Principal, IDL.Principal, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFamilyTree' : IDL.Func([], [IDL.Vec(FamilyMember)], ['query']),
    'getFamilyTreeForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(FamilyMember)],
        ['query'],
      ),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Principal], [Profile], ['query']),
    'getPublicProfiles' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func(
        [IDL.Principal, IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };