/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Relationship = IDL.Variant({
  'grandchild' : IDL.Null,
  'grandparent' : IDL.Null,
  'other' : IDL.Null,
  'child' : IDL.Null,
  'sibling' : IDL.Null,
  'spouse' : IDL.Null,
  'parent' : IDL.Null,
});
export const FamilyMember = IDL.Record({
  'id' : IDL.Nat,
  'occupation' : IDL.Text,
  'bloodType' : IDL.Text,
  'relationship' : Relationship,
  'name' : IDL.Text,
  'medicalConditions' : IDL.Vec(IDL.Text),
  'isPublic' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'occupation' : IDL.Text,
  'bloodType' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'name' : IDL.Text,
  'photoUrl' : IDL.Text,
  'isPrivate' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addFamilyMember' : IDL.Func([FamilyMember], [], []),
  'addMarriage' : IDL.Func([IDL.Principal, IDL.Principal, IDL.Text], [], []),
  'claimAdmin' : IDL.Func([], [IDL.Bool], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getFamilyTree' : IDL.Func([], [IDL.Vec(FamilyMember)], ['query']),
  'getFamilyTreeForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(FamilyMember)],
      ['query'],
    ),
  'getFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getPublicProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func(
      [IDL.Principal, IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Relationship = IDL.Variant({
    'grandchild' : IDL.Null,
    'grandparent' : IDL.Null,
    'other' : IDL.Null,
    'child' : IDL.Null,
    'sibling' : IDL.Null,
    'spouse' : IDL.Null,
    'parent' : IDL.Null,
  });
  const FamilyMember = IDL.Record({
    'id' : IDL.Nat,
    'occupation' : IDL.Text,
    'bloodType' : IDL.Text,
    'relationship' : Relationship,
    'name' : IDL.Text,
    'medicalConditions' : IDL.Vec(IDL.Text),
    'isPublic' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'occupation' : IDL.Text,
    'bloodType' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'photoUrl' : IDL.Text,
    'isPrivate' : IDL.Bool,
  });
  
  return IDL.Service({
    'addFamilyMember' : IDL.Func([FamilyMember], [], []),
    'addMarriage' : IDL.Func([IDL.Principal, IDL.Principal, IDL.Text], [], []),
    'claimAdmin' : IDL.Func([], [IDL.Bool], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getFamilyTree' : IDL.Func([], [IDL.Vec(FamilyMember)], ['query']),
    'getFamilyTreeForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(FamilyMember)],
        ['query'],
      ),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getPublicProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func(
        [IDL.Principal, IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };