/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FamilyMember {
    id: bigint;
    occupation: string;
    bloodType: string;
    relationship: Relationship;
    name: string;
    medicalConditions: Array<string>;
    isPublic: boolean;
}
export interface UserProfile {
    bio: string;
    occupation: string;
    bloodType: string;
    dateOfBirth: string;
    name: string;
    photoUrl: string;
    isPrivate: boolean;
}
export enum Relationship {
    grandchild = "grandchild",
    grandparent = "grandparent",
    other = "other",
    child = "child",
    sibling = "sibling",
    spouse = "spouse",
    parent = "parent"
}
export interface backendInterface {
    addFamilyMember(member: FamilyMember): Promise<void>;
    addMarriage(spouse1: Principal, spouse2: Principal, marriageDate: string): Promise<void>;
    claimAdmin(): Promise<boolean>;
    followUser(user: Principal): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getFamilyTree(): Promise<Array<FamilyMember>>;
    getFamilyTreeForUser(user: Principal): Promise<Array<FamilyMember>>;
    getFollowers(user: Principal): Promise<Array<Principal>>;
    getPublicProfiles(): Promise<Array<UserProfile>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isFollowing(follower: Principal, followee: Principal): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    unfollowUser(user: Principal): Promise<void>;
}
import type { FamilyMember as _FamilyMember, Relationship as _Relationship, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addFamilyMember(arg0: FamilyMember): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFamilyMember(to_candid_FamilyMember_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFamilyMember(to_candid_FamilyMember_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMarriage(arg0: Principal, arg1: Principal, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMarriage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMarriage(arg0, arg1, arg2);
            return result;
        }
    }
    async claimAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimAdmin();
            return result;
        }
    }
    async followUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFamilyTree(): Promise<Array<FamilyMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFamilyTree();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFamilyTree();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFamilyTreeForUser(arg0: Principal): Promise<Array<FamilyMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFamilyTreeForUser(arg0);
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFamilyTreeForUser(arg0);
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFollowers(arg0: Principal): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowers(arg0);
            return result;
        }
    }
    async getPublicProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicProfiles();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isFollowing(arg0: Principal, arg1: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFollowing(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFollowing(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async unfollowUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0);
            return result;
        }
    }
}
function from_candid_FamilyMember_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FamilyMember): FamilyMember {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Relationship_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Relationship): Relationship {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    occupation: string;
    bloodType: string;
    relationship: _Relationship;
    name: string;
    medicalConditions: Array<string>;
    isPublic: boolean;
}): {
    id: bigint;
    occupation: string;
    bloodType: string;
    relationship: Relationship;
    name: string;
    medicalConditions: Array<string>;
    isPublic: boolean;
} {
    return {
        id: value.id,
        occupation: value.occupation,
        bloodType: value.bloodType,
        relationship: from_candid_Relationship_n9(_uploadFile, _downloadFile, value.relationship),
        name: value.name,
        medicalConditions: value.medicalConditions,
        isPublic: value.isPublic
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    grandchild: null;
} | {
    grandparent: null;
} | {
    other: null;
} | {
    child: null;
} | {
    sibling: null;
} | {
    spouse: null;
} | {
    parent: null;
}): Relationship {
    return "grandchild" in value ? Relationship.grandchild : "grandparent" in value ? Relationship.grandparent : "other" in value ? Relationship.other : "child" in value ? Relationship.child : "sibling" in value ? Relationship.sibling : "spouse" in value ? Relationship.spouse : "parent" in value ? Relationship.parent : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FamilyMember>): Array<FamilyMember> {
    return value.map((x)=>from_candid_FamilyMember_n7(_uploadFile, _downloadFile, x));
}
function to_candid_FamilyMember_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FamilyMember): _FamilyMember {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Relationship_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Relationship): _Relationship {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    occupation: string;
    bloodType: string;
    relationship: Relationship;
    name: string;
    medicalConditions: Array<string>;
    isPublic: boolean;
}): {
    id: bigint;
    occupation: string;
    bloodType: string;
    relationship: _Relationship;
    name: string;
    medicalConditions: Array<string>;
    isPublic: boolean;
} {
    return {
        id: value.id,
        occupation: value.occupation,
        bloodType: value.bloodType,
        relationship: to_candid_Relationship_n3(_uploadFile, _downloadFile, value.relationship),
        name: value.name,
        medicalConditions: value.medicalConditions,
        isPublic: value.isPublic
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Relationship): {
    grandchild: null;
} | {
    grandparent: null;
} | {
    other: null;
} | {
    child: null;
} | {
    sibling: null;
} | {
    spouse: null;
} | {
    parent: null;
} {
    return value == Relationship.grandchild ? {
        grandchild: null
    } : value == Relationship.grandparent ? {
        grandparent: null
    } : value == Relationship.other ? {
        other: null
    } : value == Relationship.child ? {
        child: null
    } : value == Relationship.sibling ? {
        sibling: null
    } : value == Relationship.spouse ? {
        spouse: null
    } : value == Relationship.parent ? {
        parent: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
